### ISSUE TITLE
timer startet nicht bei cmd start

### ISSUE THREAD

**Issue by Matt77CHE** [oweitman/ioBroker.mytime#117]
Hallo
ich habe das Problem, dass wenn ich unter den mytime objekten beim Timer in cmd start reinschreibe, der Timer nicht startet.
Wenn ich ihn zum laufen kriege, stopt er nicht wenn er auf Null ist....
Ich habe den Adapter auch schon neu installiert - immer noch das selbe.

**Wenn der Timer auf stop steht, und ich start in cmd eingebe steht im Log:**
mytime.0 | 2021-07-10 11:10:46.657 | info | state mytime.0.Countdown.GV1.cmd changed:   (ack = true)
mytime.0 | 2021-07-10 11:10:46.653 | info | state mytime.0.Countdown.GV1.cmd changed: start  (ack = false)

**Wenn ich ihn zum Laufen bringe steht:**
mytime.0 | 2021-07-10 11:12:37.753 | info | state mytime.0.Countdown.GV1.action changed: run (ack = true)
mytime.0 | 2021-07-10 11:12:37.752 | info | state mytime.0.Countdown.GV1.end changed: 1625908417740 (ack = true)
mytime.0 | 2021-07-10 11:12:37.751 | info | state mytime.0.Countdown.GV1.start changed: 1625908357740 (ack = true)
mytime.0 | 2021-07-10 11:12:37.742 | info | state mytime.0.Countdown.GV1.cmd changed:   (ack = true)
mytime.0 | 2021-07-10 11:12:37.732 | info | state mytime.0.Countdown.GV1.cmd changed: start (ack = false)

**Wenn er läuft und ich ihn stoppen wil:**
mytime.0 | 2021-07-10 11:15:37.692 | info | state mytime.0.Countdown.GV1.cmd changed:   (ack = true)
mytime.0 | 2021-07-10 11:15:37.684 | info | state mytime.0.Countdown.GV1.cmd changed: stop  (ack = false)

**Wenn er läuft und ich ihn stoppen kann:**
mytime.0 | 2021-07-10 11:16:18.054 | info | state mytime.0.Countdown.GV1.action changed: stop (ack = true)
mytime.0 | 2021-07-10 11:16:18.053 | info | state mytime.0.Countdown.GV1.end changed: 0 (ack = true)
mytime.0 | 2021-07-10 11:16:18.051 | info | state mytime.0.Countdown.GV1.start changed: 0 (ack = true)
mytime.0 | 2021-07-10 11:16:18.047 | info | state mytime.0.Countdown.GV1.cmd changed:   (ack = true)
mytime.0 | 2021-07-10 11:16:18.041 | info | state mytime.0.Countdown.GV1.cmd changed: stop (ack = false)

Damit er den Befehl annimmt, muss ich zuerst den Befehl (zb stop) als bestätigt senden, dann einen leeren unbestätigten Befehl, dann den Befehl (zb stop) wieder als unbestätigt senden.

- Adapter Version: 0.6.1
 - JS-Controller version: 3.3.14
 - Node version: 12.22.2
 - Operating system: Ubuntu 18.04.5

Woran könnte dies liegen?

**Comment by oweitman** [comment]
hm, sorry für delay. im sommer ist der suppo9rt immer etwas reduziert.
ich hab das problem noch nicht ganz verstanden.

zum hintergrund:
die datenpunkte ändern sich nicht sekündlich. da würden zuviele daten auf der kommunikationsebene unnötigerweise erzeugt werden.
bei start wird die start zeit und die ende zeit berechnet.
wenn die ende zeit erreicht wird, dann wird status auf end gesetzt.

probiere folgendes aus:
setze in cmd den folgenden wert für countdown auf 20 sekunden
`=00:20`
Ergebnis: Der Datenpunkt timer wird auf 20000 gesetzt, da 20 sekunden = 20000 milisekunden entspricht
dann setze in cmd den start befehl
`start`
die datenpunkte end und start werden berechnet und gesetzt
nach 20 sekunden (nachdem die zeit im endpunkt end erreicht ist) wird der datenpunkt status auf "end" gesetzt.
ein trigger auf status lässt dich alle wichtigen ereignisse mitbekommen

wenn du den countdown visualisiert haben möchtest, dann verwende die widgets für vis.
falls was fehlt, schreibe hier oder im forum bei https://forum.iobroker.net/topic/33376/test-adapter-mytime-v0-1-x?_=1626717106520

**Comment by Matt77CHE** [comment]
Hallo
Da die Zeiten nicht gestartet sind mit dem cmd Befehl (sowohl in den widgets in der Vis als auch in den Objekten) habe ich den Adapter gelöscht und das Ganze durch eigene Datenpunkte erledigt.
