### ISSUE TITLE
File tab_m.html not found

### ISSUE THREAD

**Issue by crunchip77** [oweitman/ioBroker.mytime#139]
Beim Aufruf aus dem linken Reiter erscheint File tab_m.html not found.
v.0.7.5
![image](https://user-images.githubusercontent.com/41550245/128626691-40f6018b-3546-4178-948b-a65bdabcfab8.png)

**Comment by oweitman** [comment]
fixed in v0.7.6
zum tatsächlichen entfernen des Reiters muss der Adapter gelöscht und neu installiert werden.
