### ISSUE TITLE
VIS Widget: timer not updated if changing timer value

### ISSUE THREAD

**Issue by Scrounger** [oweitman/ioBroker.mytime#187]
**Describe the bug**  
If countdown is running and you change the timer interval, the widget timer text will not be updated.

**To Reproduce**  
1. start countdown over dp '.cmd' with command 'start'
2. change dp '.timer' to a new value

**Expected behavior**  
Widget timer text should be updated

**Screenshots & Logfiles**  
![mytimer_widget_bug](https://user-images.githubusercontent.com/6370451/146750028-4a570a29-8ca9-4b64-8606-d6f09c35940a.gif)

**Versions:**  
 - Adapter version: 0.7.6
 - JS-Controller version: 3.3.21

**Comment by oweitman** [comment]
yes this is correct.
the new target time is only calculated at timer start.
