### ISSUE TITLE
myTime Widget nicht initialisiert nach VIS neustart

### ISSUE THREAD

**Issue by looxer01** [oweitman/ioBroker.mytime#226]
Hi
das von mir verwendete myTime Widget muss immer wieder initialisiert werden (z.B. ein count down timer gesetzt werden) damit das Widget korrekt angezeigt wird.
Nach einem Start wird das Widget wieder nicht initialisiert angezeigt.
Das Verhalten kann ich erst seit einem der letzten updates beobachten.

vG Looxer

![myTime1](https://user-images.githubusercontent.com/11609655/151125522-77612552-452a-48fe-8497-3b12a19ea378.JPG)
![myTime2](https://user-images.githubusercontent.com/11609655/151125538-bd2868bb-aa73-4d7f-a437-a5698bf3e837.JPG)

**Comment by oweitman** [comment]
habe gerade auf meiner testinstallation mit der letzten version probiert.
kann beim widget co9untdown circle jetzt kein problem feststellen.
kannst du mir bitte die folgenden informationen mitteilen:
versionen der folgenden adapter
js-controller
vis
mywidget
welchen browser in welcher version auf was für einem gerät verwendest du?
wie sind die genauen timer einstellungen (mytime-konfigurations-dialog)
wie sind deine einstellungen des countdown circle widgets
und die Einstellungen deines start knopfs
gern können wir auch hier weitermachen
https://forum.iobroker.net/topic/33376/test-adapter-mytime-v0-1-x/310

**Comment by looxer01** [comment]
Der Wechsel von Datenpunkt "action" auf "timer" hat das Problem gelöst.
Das Design sollte zwar so nicht reagieren, allerdings weist ja auch die Doku darauf hin, den Datenpunkt "timer" zu verwenden.
Daher ist aus meiner Sicht das Problem erledigt.
Vielen Dank für die Unterstützung.
