### ISSUE TITLE
Widgets not available

### ISSUE THREAD

**Issue by thomke67** [oweitman/ioBroker.mytime#271]
Hi,

after the installation of the adapter, I do not see any widget in the vis. 

![grafik](https://user-images.githubusercontent.com/57798896/157256665-f957be44-e146-43fc-84b4-ec8078375cf5.png)

**Versions:**  
 - Adapter version: v0.7.6
 - JS-Controller version: 4.0.18
 - Node version: Node.js: v12.22.10 NPM: 6.14.16
 - Operating system: Raspberian

Regards,
Thomas

**Comment by thomke67** [comment]
Sorry, I forgot to re-start the vis.......

**Comment by oweitman** [comment]
ja der vis adapter sollte von iobroker automatisch nach installation neu gestartet werden
https://github.com/oweitman/ioBroker.mytime/blob/afa899bae0f2d50de4e4cdeda63b29528e7cd996/io-package.json#L149
