### ISSUE TITLE
Running Timer are resetted after restart of adapter

### ISSUE THREAD

**Issue by oweitman** [oweitman/ioBroker.mytime#357]

**Comment by Matt77CHE** [comment]
Ich habe bei mir mal den Adapter auf Silly gestellt, den Adapter gestoppt, eingeschlaten, Timer auf 30s gestellt und den Adapter neu gestartet- hier das Log:
`<html>
<body>


mytime.0 | 2022-06-15 17:40:34.838 | info | state mytime.0.Countdown.GV01.cmd changed: (ack = true)
-- | -- | -- | --
mytime.0 | 2022-06-15 17:40:34.838 | silly | doStateChange
mytime.0 | 2022-06-15 17:40:34.837 | info | state mytime.0.Countdown.GV01.start changed: 0 (ack = true)
mytime.0 | 2022-06-15 17:40:34.836 | silly | States user redis pmessage mytime.0.*/mytime.0.Countdown.GV01.cmd:{"val":" ","ack":true,"ts":1655307634827,"q":0,"from":"system.adapter.mytime.0","user":"system.user.admin","lc":1654979800436}
mytime.0 | 2022-06-15 17:40:34.836 | silly | States user redis pmessage mytime.0.*/mytime.0.Countdown.GV01.start:{"val":0,"ack":true,"ts":1655307634827,"q":0,"from":"system.adapter.mytime.0","user":"system.user.admin","lc":1654979800438}
mytime.0 | 2022-06-15 17:40:34.836 | silly | doStateChange
mytime.0 | 2022-06-15 17:40:34.835 | info | state mytime.0.Countdown.GV01.action changed: stop (ack = true)
mytime.0 | 2022-06-15 17:40:34.835 | silly | doStateChange
mytime.0 | 2022-06-15 17:40:34.835 | info | state mytime.0.Countdown.GV01.timer changed: 0 (ack = true)
mytime.0 | 2022-06-15 17:40:34.833 | silly | States user redis pmessage mytime.0.*/mytime.0.Countdown.GV01.action:{"val":"stop","ack":true,"ts":1655307634824,"q":0,"from":"system.adapter.mytime.0","user":"system.user.admin","lc":1654997960716}
mytime.0 | 2022-06-15 17:40:34.832 | silly | States user redis pmessage mytime.0.*/mytime.0.Countdown.GV01.timer:{"val":0,"ack":true,"ts":1655307634819,"q":0,"from":"system.adapter.mytime.0","user":"system.user.admin","lc":1655307634819}
mytime.0 | 2022-06-15 17:40:34.830 | silly | doStateChange
mytime.0 | 2022-06-15 17:40:34.829 | info | state mytime.0.Countdown.GV01.end changed: 0 (ack = true)
mytime.0 | 2022-06-15 17:40:34.828 | silly | doStateChange
mytime.0 | 2022-06-15 17:40:34.827 | info | state mytime.0.Countdown.GV01.config changed: {"stopbehaviour":"timer"} (ack = true)
mytime.0 | 2022-06-15 17:40:34.826 | silly | States user redis pmessage mytime.0.*/mytime.0.Countdown.GV01.end:{"val":0,"ack":true,"ts":1655307634819,"q":0,"from":"system.adapter.mytime.0","user":"system.user.admin","lc":1654979800438}
mytime.0 | 2022-06-15 17:40:34.825 | silly | States user redis pmessage mytime.0.*/mytime.0.Countdown.GV01.config:{"val":"{\"stopbehaviour\":\"timer\"}","ack":true,"ts":1655307634819,"q":0,"from":"system.adapter.mytime.0","user":"system.user.admin","lc":1654975894841}
mytime.0 | 2022-06-15 17:40:34.822 | silly | doStateChange
mytime.0 | 2022-06-15 17:40:34.821 | info | state mytime.0.Countdown.GV01.name changed: GV01 (ack = true)
mytime.0 | 2022-06-15 17:40:34.820 | silly | States user redis pmessage mytime.0.*/mytime.0.Countdown.GV01.name:{"val":"GV01","ack":true,"ts":1655307634818,"q":0,"from":"system.adapter.mytime.0","user":"system.user.admin","lc":1654975894894}
mytime.0 | 2022-06-15 17:40:34.816 | debug | setState cmd " "
mytime.0 | 2022-06-15 17:40:34.816 | debug | setState start 0
mytime.0 | 2022-06-15 17:40:34.816 | debug | setState action "stop"
mytime.0 | 2022-06-15 17:40:34.816 | debug | setState timer 0
mytime.0 | 2022-06-15 17:40:34.815 | debug | setState end 0
mytime.0 | 2022-06-15 17:40:34.815 | debug | setState config "{\"stopbehaviour\":\"timer\"}"
mytime.0 | 2022-06-15 17:40:34.814 | debug | setState name "GV01"
mytime.0 | 2022-06-15 17:40:34.813 | silly | doStateChange
mytime.0 | 2022-06-15 17:40:34.813 | info | state mytime.0.info.connection changed: true (ack = true)
mytime.0 | 2022-06-15 17:40:34.812 | silly | States user redis pmessage mytime.0.*/mytime.0.info.connection:{"val":true,"ack":true,"ts":1655307634806,"q":0,"from":"system.adapter.mytime.0","user":"system.user.admin","lc":1655307634806}
mytime.0 | 2022-06-15 17:40:34.812 | silly | clearTimeout doObserverServerTimeseries
mytime.0 | 2022-06-15 17:40:34.812 | silly | setTimeout doObserverServerTimeseries
mytime.0 | 2022-06-15 17:40:34.811 | silly | getDateList
mytime.0 | 2022-06-15 17:40:34.811 | silly | checkTimeseriesStatus
mytime.0 | 2022-06-15 17:40:34.810 | silly | doObserverServerTimeseries
mytime.0 | 2022-06-15 17:40:34.809 | debug | createObject cmd
mytime.0 | 2022-06-15 17:40:34.808 | debug | createObject start
mytime.0 | 2022-06-15 17:40:34.808 | debug | createObject action
mytime.0 | 2022-06-15 17:40:34.808 | debug | createObject timer
mytime.0 | 2022-06-15 17:40:34.808 | debug | createObject end
mytime.0 | 2022-06-15 17:40:34.808 | debug | createObject config
mytime.0 | 2022-06-15 17:40:34.807 | debug | createObject name
mytime.0 | 2022-06-15 17:40:34.743 | silly | doStateChange
mytime.0 | 2022-06-15 17:40:34.743 | info | state mytime.0.info.connection changed: false (ack = true)
mytime.0 | 2022-06-15 17:40:34.742 | silly | States user redis pmessage mytime.0.*/mytime.0.info.connection:{"val":false,"ack":true,"ts":1655307634739,"q":0,"from":"system.adapter.mytime.0","user":"system.user.admin","lc":1655307630917}
mytime.0 | 2022-06-15 17:40:34.730 | silly | States system redis pmessage system.adapter.mytime.0.logLevel/system.adapter.mytime.0.logLevel:{"val":"silly","ack":true,"ts":1655307634722,"q":0,"from":"system.adapter.mytime.0","lc":1655307444837}
mytime.0 | 2022-06-15 17:40:34.721 | silly | clearTimeout doObserverServerCountdown
mytime.0 | 2022-06-15 17:40:34.721 | silly | setTimeout doObserverServerCountdown
mytime.0 | 2022-06-15 17:40:34.720 | silly | getCountdownInfo {}
mytime.0 | 2022-06-15 17:40:34.720 | silly | checkCountdownStatus
mytime.0 | 2022-06-15 17:40:34.720 | silly | doObserverServerCountdown
mytime.0 | 2022-06-15 17:40:34.720 | silly | readTimeseriesInfo
mytime.0 | 2022-06-15 17:40:34.720 | debug | setTimeseriesInfo {}
mytime.0 | 2022-06-15 17:40:34.719 | silly | readCountdownInfo
mytime.0 | 2022-06-15 17:40:34.719 | debug | setCountdownInfo {"GV01":{"name":"GV01","config":"{\"stopbehaviour\":\"timer\"}","end":0,"timer":0,"action":"stop","start":0,"cmd":" "}}
mytime.0 | 2022-06-15 17:40:34.719 | debug | setState connection true
mytime.0 | 2022-06-15 17:40:34.719 | debug | init
mytime.0 | 2022-06-15 17:40:34.718 | debug | main onReady open mytime
mytime.0 | 2022-06-15 17:40:34.717 | debug | main onReady start
mytime.0 | 2022-06-15 17:40:34.705 | info | starting. Version 0.7.12 in /opt/iobroker/node_modules/iobroker.mytime, node: v14.19.3, js-controller: 4.0.23
mytime.0 | 2022-06-15 17:40:30.919 | silly | States user redis pmessage mytime.0.*/mytime.0.info.connection:{"val":false,"ack":true,"ts":1655307630917,"q":0,"from":"system.adapter.mytime.0","user":"system.user.admin","lc":1655307630917}
mytime.0 | 2022-06-15 17:40:30.890 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mytime.0 | 2022-06-15 17:40:30.890 | info | terminating


</body>
</html>`

**Comment by oweitman** [comment]
kannst du das mit der nächsten version ab >1.1.0 nochmal prüfen bitte
