### ISSUE TITLE
Timerwerte nicht editierter über VIS

### ISSUE THREAD

**Issue by freaktech** [oweitman/ioBroker.mytime#436]
Hallo!

Ich verwenden den Timer seit ein paar Tagen
aus der VIS überschreibe ich den Timer mit + - Buttons

leider werden bei Neustart des Adapters diese Werte wieder überschrieben

könnte man das fixen?

bei Erstellung war das 1 Minute
hier ändere ich es zb auf 8 das klappt alles super

jedoch nach Neustart ist es wieder ne 1

danke
tom

**Comment by oweitman** [comment]
Ja der Adapter muss überarbeitet werden, da die Admin Struktur sich geändert hat.
Kann noch ein wenig dauern, da ich aktuell noch andere Projekte laufen habe.

**Comment by oweitman** [comment]
was lange währt.
in der version >1.0.15 dürfte das Problem nicht mehr auftreten.
In den Einstellungen bleibt allerdings der ursprünglich eingestellte Wert bestehen,
aber der timer datenpunkt wird bei neustart nicht mehr überschrieben.

**Comment by freaktech** [comment]
danke

den Satz versteh ich aber nicht

In den Einstellungen bleibt allerdings der ursprünglich eingestellte Wert bestehen,

wenn ich den Datenpunkt verändert und der Adapter neu startet bleibt dann mein Wert?

**Comment by oweitman** [comment]
ich bezweifle das du das schon ausprobieren konntest, da die version noch gar nicht im beta repo angekommen ist.

es gibt einmal die adapter einstellungen, die du über das werkzeugschlüssel icon aufrufst und neue countdown timer anlegen kannst. das führt dazu, das die datenpunkte für den countdown angelegt werden.
wenn du nun befehle wie bspw =1000 im datenpunkt cmd eingibst, wird der datenpunkt timer verändert.
diese veränderung wird aber nicht automatisch in die adapterkonfiguration zurück gespielt.

dein problem war ja, wenn ich es richtig verstanden habe, das bei neustart die adapter konfiguration die datenpunkte wieder überschreibt und die durch =1000 eingestellte timerlänge dann wieder überschrieben wird.

es gibt zwar einen befehl save (der aktuell noch nicht funktioniert). problem ist aber, sobald die adapter konfiguration beschrieben wird, erzwingt iobroker einen adapter neustart.
