### ISSUE TITLE
Please sync "adapter type" to repo

### ISSUE THREAD

**Issue by Apollon77** [oweitman/ioBroker.mytime#7]
Repo: https://github.com/ioBroker/ioBroker.repositories/blob/master/sources-dist.json#L988 "general"
io-package: visualization

Please sync both places, best create a repo PR to fix it there to visualisation

Thank you

**Comment by oweitman** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/1035

**Comment by Apollon77** [comment]
thank you!
