### ISSUE TITLE
Please remove vis from io-package dependancies

### ISSUE THREAD

**Issue by ldittmar81** [oweitman/ioBroker.mytime#706]
This adapter doesn't require VIS to function; it can be used independently without VIS.

**Comment by oweitman** [comment]
but it contains widgets

**Comment by oweitman** [comment]
But that depends on the way you look at it. My adapters are aimed more at those with less IT skills and therefore want to use the VIS functionality directly.
Anyone who doesn't need vis can remove it again by pressing a button.
Maybe you (iobroker core team) should create a guideline about what is recommended and when.
I had been asking for a while (about 2 years ago) whether widgets and server logic should be in different adapters. now recently also on discord whether you can/should pack vis1 and vis2 widgets in one adapter or create a 2. adapter with the vis2 widgets and double the server functionality. Unfortunately there is no recommendation yet.

**Comment by ldittmar81** [comment]
> Anyone who doesn't need vis can remove it again by pressing a button.

The problem is that I must install vis, if I want to use your adapter and than I cant delete vis because of your adapter, because if I try it, I will get an error.

> Maybe you (iobroker core team) should create a guideline about what is recommended and when.

We have next week a meeting and I will take this point

> the create-adapter script actualy also creates the vis dependency if you say that widgets are included

Ohh... that is a point. We need to change this. I will create a issue. Thanks

**Comment by oweitman** [comment]
removed in >v1.1.0
