### ISSUE TITLE
Not able to install in ioBroker

### ISSUE THREAD

**Issue by TPPTim** [oweitman/ioBroker.mytime#839]
**Describe the bug**  
I am not able to install the adapter in ioBroker. It is not available at NPM and Github. An manual installation from github.com/oweitman/iobroker.mytime results in error.

**Versions:**  
 - Adapter version: <latest>
 - JS-Controller version: <v18.19.0>
 - NPM version: <10.2.3>

**Additional context**  

![Screenshot_20240909-081128](https://github.com/user-attachments/assets/83e0aca1-1894-4861-8126-0c72f02538b1)
![Screenshot_20240909-081135](https://github.com/user-attachments/assets/f7d0dbad-65fc-4180-ad43-3a2425fb84e8)

**Comment by oweitman** [comment]
https://www.npmjs.com/package/iobroker.mytime

Due to changes of the iobroker gui (react)
the settings dialog is not functional
but The install should work.
Can you please post the content (as text) of the detailed log?

**Comment by TPPTim** [comment]
Hey Oweitman,
Thanks for your super quick reply. I tried it again and it worked fine as you wrote above.
The only thing I saw was that the timer adapter did not start.
(https://github.com/user-attachments/assets/b1182c59-f6ba-4ecc-ac22-d5ae04453fcd)

The timer wants to install vis. I only use vis2. Is vis required to use the functionality?
![grafik](https://github.com/user-attachments/assets/a680057d-f558-4bdd-a6e0-f65f1c4412bf)

Thanks a lot for your help!
Tim

**Comment by oweitman** [comment]
No. But the adapter contains some widgets.
You can simply remove vis after installation
In the next major release the settings gui is updated and the vis dependency is removed 
Actual I have problems with the layout and my personal time.
It maybe took some time

**Comment by TPPTim** [comment]
OK, I will test it today at home and come back to you.

**Comment by TPPTim** [comment]
Good morning,
With vis installed I was able to start the adapter.
I created a new timer and tried to start it with the start command. Now there are 2 timestamps for start and end. But I cannot find a countdown value that is decreasing. Does your adapter provide such a countdown value or do I have to calculate it myself using a script?

Thank you very much!
Tim

**Comment by oweitman** [comment]
A timer only saves the start and end. The continuous update of a data point would be very resource -intensive, and the current value would usually not be correct anyway.
The main goal is that after a timer has expired, a data point is being triggered, on which script can then be listening and any actions can be done.

If you want to have a visual count-down, you can take a look at one of the VIS1 widgets. The calculation of the time runs in the widget, i.e. in the browser
If you want to check the code, how I implemented it, you will also find the widget code in the repositiory

**Comment by TPPTim** [comment]
OK, I get it, that makes sense.
I have tried to use the timer widgets you have developed. The "timer" datapoint is selected as the countdown_oid, but the countdown is not displayed. Is it basically possible to use the widgets in vis2?

**Comment by oweitman** [comment]
No, the actual version didn’t work in vis2
I work on a new version that is compatible with the actual admin version of Iobroker and I hope that I also get the widgets compatible with vis2

**Comment by oweitman** [comment]
adapter has been completely revised in >v1.1.0
widgets for vis 1 should work.
vis 2 widgets will follow when the remaining work is completed.
