### ISSUE TITLE
Feature request: "reverse Countdown" or "time since"

### ISSUE THREAD

**Issue by fabiankrauss** [oweitman/ioBroker.mytime#85]
Hi,

I would like a new feature that says how much time has passed since the set value in the data point.
Output as datapoints in days and weeks would also be great.
Use case:
My wife keeps asking how old our puppy is (in weeks).

Of course you can do this as a script but think it would fit nicely in the adapter.

**Comment by oweitman** [comment]
hm, ok, like the reverse function of the countdown.
i think about it

**Comment by oweitman** [comment]
In Version 0.7.10 i added a reverse countdown widget
