### ISSUE TITLE
test Text sichtbar in der vis

### ISSUE THREAD

**Issue by Brainbug01** [oweitman/ioBroker.mytime#864]
Aktuell V1.2.1

Zeile 31 ist in der vis zusehen:
https://github.com/oweitman/ioBroker.mytime/blob/main/widgets/mytime.html

Beitrag im Forum zum anschauen:
https://forum.iobroker.net/topic/78123/vis-ladebildschirm-steht-oben-links-test

**Comment by oweitman** [comment]
in v1.2.2 behoben
